kind: PersistentVolume
apiVersion: v1
metadata:
  name: historical-pv
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /druidpv/historical
